Repository Alvarado007/Cuarto-miniproyecto-Java-persistencia-en-memoria, pull requests merged in 2025-06, with the labels that each got.

#4 Funcionalidad Guardar
  src/Clases/Ataque.java
  src/Clases/Entrenador.java
  src/Clases/Pokemon.java
  src/Clases/SerVivo.java
  src/Controladores/ControladorSeleccion.java
  src/Vistas/SeleccionPokemon.java
  src/Vistas/SeleccionPokemonTerminal.java
Labels: help wanted

#6 Funcionalidad Cargar
  src/Controladores/ControladorInicio.java
  src/Vistas/InicioPokemon.java
  src/Vistas/InicioPokemonTerminal.java
Labels: help wanted

#10 Boton ver movimientos
  bin/Guardados/a.txt
  bin/Guardados/s.txt
  bin/Imagenes/Logos/Ver Movimientos.png
  src/Guardados/a.txt
  src/Guardados/s.txt
  src/Imagenes/Logos/Ver Movimientos.png
  src/Vistas/SeleccionPokemon.java
Labels: New

#12 Funcionalidad pila
  bin/Guardados/a.txt
  bin/Guardados/aaa.txt
  bin/Guardados/aaaaa.txt
  bin/Guardados/d.txt
  bin/Guardados/f.txt
  bin/Guardados/saa.txt
  src/Controladores/ControladorBatalla.java
  src/Controladores/ControladorSeleccion.java
  src/Guardados/a.txt
  src/Guardados/aaa.txt
  src/Guardados/aaaaa.txt
  src/Guardados/d.txt
  src/Guardados/f.txt
  src/Guardados/saa.txt
  src/Vistas/SeleccionPokemon.java
Labels: enhancement

#15 Se agregan comentarios de complemento en todo el código
  bin/Guardados/asd.txt
  bin/Guardados/qwe.txt
  src/App.java
  src/Clases/Batalla.java
  src/Clases/Entrenador.java
  src/Clases/Pokemon.java
  src/Controladores/ControladorBatalla.java
  src/Controladores/ControladorEntrenadores.java
  src/Controladores/ControladorInicio.java
  src/Controladores/ControladorSeleccion.java
  src/Guardados/asd.txt
  src/Guardados/qwe.txt
  src/Vistas/BatallaPokemon.java
  src/Vistas/BatallaPokemonTerminal.java
  src/Vistas/Entrenadores.java
  src/Vistas/EntrenadoresTerminal.java
  src/Vistas/InicioPokemon.java
  src/Vistas/InicioPokemonTerminal.java
  src/Vistas/SeleccionPokemon.java
  src/Vistas/SeleccionPokemonTerminal.java
Labels: documentation
